### ISSUE TITLE
Could I use formula type by using this library?

### ISSUE THREAD

**Issue by mind9063** [LuudJanssen/react-native-webview-quill#28]
Hi, I saw that insert statements that return texts work well.
And then, I tried to use formula type text like e=mc^2. However {insert:{formula:'e=mc^2'}} format returned nothing. Also it prevented rendering subsequent insert statements.
I know that to use this formula type in quill, it needs to integrate Katex. Is there a way to use formula in this library without it? Or is it structurally possible for me to integrate katex with this library? 
Thank you.

**Comment by LuudJanssen** [comment]
Hi @mind9063. This component is a webview containing [the Quill text editor](https://quilljs.com/). For this to work you would have to insert the KaTeX library into the webview [here](https://github.com/LuudJanssen/react-native-webview-quill/blob/develop/src/components/Quill/resources/generateWebViewIndex.ts).

I personally don't have time to add this feature. But for your case you could fork the repository and simply insert the KaTeX script tag into the webview html and enable the formula toolbar, hat should work.

**Comment by LuudJanssen** [comment]
@mind9063, let me know if you want to create a PR for this and if you need any help with that. Closing this issue for now.
